version: '3.9'

services:
  too-doo-database:
    container_name: too-doo-database
    image: postgres:alpine
    restart: always
    ports:
      - '47385:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: too-doo-database
